/**
 * This file was automatically generated by the Mule ESB Maven Tools
 */
package com.veamospues.muleapp;

import com.veamospues.mule.config.builders.SpringAnnotationConfigurationBuilder;
import org.junit.Test;
import org.mule.DefaultMuleMessage;
import org.mule.api.MuleMessage;
import org.mule.api.client.MuleClient;
import org.mule.api.config.ConfigurationBuilder;
import org.mule.tck.junit4.FunctionalTestCase;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

public class CustomBuilderTestCase extends FunctionalTestCase {
  private static final int RECEIVE_TIMEOUT = 5000;
  public static final String CONFIG_FILE = "src/main/app/mule-config.xml";

  @Override
  protected String getConfigFile() {
    return CONFIG_FILE;
  }

  @Override
  protected ConfigurationBuilder getBuilder() throws Exception {
    return new SpringAnnotationConfigurationBuilder(this.getConfigFile());
  }

  @Test
  public void checkThatSpringBeanIsCalledInFlow() throws Exception {
    MuleClient client = muleContext.getClient();
    MuleMessage message = new DefaultMuleMessage("world", muleContext);

    client.dispatch("vm://in", message);

    MuleMessage resultMessage = client.request("vm://out", RECEIVE_TIMEOUT);

    assertEquals("Hello from dummy service!", resultMessage.getPayloadAsString());
  }
}
